version: '3.9'
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379

  elastic_search:
    image: elasticsearch:8.6.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - elastic_volume:/usr/share/elasticsearch/data
    healthcheck:
      test: curl -s http://127.0.0.1:9200 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 50
    ports:
      - 9200:9200

volumes:
  elastic_volume:
