version: '3.9'
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379

  elastic_search:
    image: elasticsearch:8.6.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    healthcheck:
      test: curl -s http://127.0.0.1:9200 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 50
    ports:
      - 9200:9200

  postgres:
    image: postgres:13.0-alpine
    env_file:
      - ./configs/.env
    volumes:
      - dbdata:/var/lib/postgresql/data/
      - ./dump/backup.sql:/docker-entrypoint-initdb.d/dump.sql:ro
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d movies_database"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped


volumes:
  dbdata:
