version: '3.9'
services:
  elastic_dump:
    image: elasticdump/elasticsearch-dump:latest
    volumes:
      - ./dump/:/backup/
      - ./scripts/:/scripts/
    network_mode: host

    

      

    # command: >
    #   elasticdump \
    #     --input=http://127.0.0.1:9200 \
    #     --output=/backup/es_dump.json \
    #     --type=data
      
    
    